#pragma once

using namespace ATL;

template <class T>
class CProxy_IMainWndEvents : public IConnectionPointImpl<T, &__uuidof( _IMainWndEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
